### ISSUE TITLE
'npm start 'fails

### ISSUE THREAD

**Issue by mmport80** [sencha/extjs-reactor#217]
I followed the steps in the readme and this is the result. On Ubuntu16.10.

```
> webpack-dev-server --progress --colors

 10% building modules 1/1 modules 0 activeevents.js:163                            
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 127.0.0.1:8080
    at Object.exports._errnoException (util.js:1050:11)
    at exports._exceptionWithHostPort (util.js:1073:20)
    at Server.setupListenHandle [as _listen2] (net.js:1259:14)
    at listenInCluster (net.js:1307:12)
    at doListen (net.js:1432:7)
    at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:62:16)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:78:10)

npm ERR! Linux 4.8.0-51-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @extjs/reactor-boilerplate@1.0.0 start: `webpack-dev-server --progress --colors`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @extjs/reactor-boilerplate@1.0.0 start script 'webpack-dev-server --progress --colors'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the @extjs/reactor-boilerplate package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack-dev-server --progress --colors
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs @extjs/reactor-boilerplate
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls @extjs/reactor-boilerplate
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/john/.npm/_logs/2017-05-23T12_28_49_870Z-debug.log
```

**Comment by mmport80** [comment]
port already in use - my mistake!
