### ISSUE TITLE
Module build failed: SyntaxError: Unexpected token {

### ISSUE THREAD

**Issue by gduggirala** [sencha/extjs-reactor#41]
When executing the command npm start I am getting the following error.
I didn't make any code changes.

```
 npm start

> @extjs/reactor-boilerplate@0.2.6 start /home/gduggirala/react-samples/extjs-reactor/packages/reactor-boilerplate
> webpack-dev-server --progress --profile --colors --config webpack.config.dev.js
                                                                                                                                             70% 1/1 build modules http://localhost:8080/webpack-dev-server/
webpack result is served from /
content is served from ./build                                                                                                        1m7ms op 90% optimize assets
building Ext JS bundle: ext => build/extjs
Sencha Cmd v6.2.1.29
[INF] Loading app json manifest...
[INF] Writing concatenated output to file /home/gduggirala/react-samples/extjs-reactor/packages/reactor-boilerplate/build/extjs/ext.js
[INF] Appending concatenated output to file /home/gduggirala/react-samples/extjs-reactor/packages/reactor-boilerplate/build/extjs/ext.js
[INF] writing sass content to ext.scss
[INF] appending sass content to ext.scss
[INF] appending sass content to ext.scss
[INF] merging 381 input resources into /home/gduggirala/react-samples/extjs-reactor/packages/reactor-boilerplate/build/extjs/resources
[INF] merged 381 resources into /home/gduggirala/react-samples/extjs-reactor/packages/reactor-boilerplate/build/extjs/resources
[INF] merging 6 input resources into /home/gduggirala/react-samples/extjs-reactor/packages/reactor-boilerplate/build/extjs/resources
[INF] merged 6 resources into /home/gduggirala/react-samples/extjs-reactor/packages/reactor-boilerplate/build/extjs/resources
[LOG] Building /home/gduggirala/react-samples/extjs-reactor/packages/reactor-boilerplate/build/extjs/ext.scss
Exiting with code 0
[INF] Waiting for changes...                                                                                                               13228ms optimi3ms emit 
Hash: d5ea1a0c465c40eb75a2
Version: webpack 1.14.0
Time: 14132ms
     Asset       Size  Chunks             Chunk Names
  index.js    3.55 kB       0  [emitted]  main
index.html  481 bytes          [emitted]  
chunk    {0} index.js (main) 28 bytes [rendered]
    [0] multi main 28 bytes {0} [built] [1 error]
       factory:0ms building:1ms = 1ms
chunk {9999} extjs/ext.js, extjs/ext.css (extjs-js) 0 bytes

ERROR in ./src/index.js
Module build failed: SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at /home/gduggirala/react-samples/extjs-reactor/packages/reactor-boilerplate/node_modules/babel-core/lib/transformation/file/options/option-manager.js:174:20
    at Array.map (native)
    at Function.normalisePlugins (/home/gduggirala/react-samples/extjs-reactor/packages/reactor-boilerplate/node_modules/babel-core/lib/transformation/file/options/option-manager.js:154:20)
    at OptionManager.mergeOptions (/home/gduggirala/react-samples/extjs-reactor/packages/reactor-boilerplate/node_modules/babel-core/lib/transformation/file/options/option-manager.js:229:36)
    at OptionManager.init (/home/gduggirala/react-samples/extjs-reactor/packages/reactor-boilerplate/node_modules/babel-core/lib/transformation/file/options/option-manager.js:374:12)
    at File.initOptions (/home/gduggirala/react-samples/extjs-reactor/packages/reactor-boilerplate/node_modules/babel-core/lib/transformation/file/index.js:216:65)
    at new File (/home/gduggirala/react-samples/extjs-reactor/packages/reactor-boilerplate/node_modules/babel-core/lib/transformation/file/index.js:139:24)
    at Pipeline.transform (/home/gduggirala/react-samples/extjs-reactor/packages/reactor-boilerplate/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/home/gduggirala/react-samples/extjs-reactor/packages/reactor-boilerplate/node_modules/babel-loader/lib/index.js:38:20)
    at Object.module.exports (/home/gduggirala/react-samples/extjs-reactor/packages/reactor-boilerplate/node_modules/babel-loader/lib/index.js:133:12)
 @ multi main
Child html-webpack-plugin for "index.html":
    chunk    {0} index.html 541 kB [rendered]
        [0] ./~/html-webpack-plugin/lib/loader.js!./src/index.html 661 bytes {0} [built]
           factory:38ms building:40ms = 78ms
        [1] ./~/html-webpack-plugin/~/lodash/lodash.js 540 kB {0} [built]
           [0] 78ms -> factory:299ms building:477ms = 854ms
        [2] (webpack)/buildin/module.js 251 bytes {0} [built]
           [0] 78ms -> [1] 776ms -> factory:2ms building:3ms = 859ms


```

**Comment by markbrocato** [comment]
That's odd.  I just cloned a fresh copy of the repo, ran through the instructions on packages/reactor-boilerplate/README.md, and everything is working fine.  Ran it on another machine just to be sure and everything was fine.  Are you sure there isn't something funny going on with your environment in general?  Perhaps an older version of node?

**Comment by markbrocato** [comment]
FWIW, another user had the same problem.  He was running node 4.  Upgrading to node 6 fixed the issue.
