### ISSUE TITLE
Rhino Parse Error using DisplayField with Image as Value

### ISSUE THREAD

**Issue by BlaineBradbury** [sencha/extjs-reactor#76]
Sencha cmd seems to be throwing an error when I have an image path value in a DisplayField like this:
```
     <DisplayField name='adi_search_icon'
            labelWidth={20}
            minWidth={20}
            value='<img src="icons/toolbar_find.png"></img>'
     />
```
If I leave the value as a number or some other string it builds and displays, but the image does not.

It works in my non-React extjs prototype as this in items:
```
     {xtype: 'displayfield',name: 'adi_search_icon',labelWidth: 20,minWidth: 20,value: '<img 
     src="icons/toolbar_find.png"></img>'}
```
```
Error:
Sencha Cmd v6.2.1.29
[INF] Loading app json manifest...
[ERR] C2000: Rhino Parse Error (missing } after property list => Ext.create({xtype: "displayfield", name: "search_icon", labelWidth: 20, minWidth: 20, value: "<img src="icons/toolbar_find.png"></img>"});) -- /WebServer/myapp/extjs-reactor/packages/reactor-classic-boilerplate/build/extjs/manifest.js:327:114
[ERR] C2000: Rhino Parse Error (Compilation produced 1 syntax errors. => null) -- /WebServer/myapp/extjs-reactor/packages/reactor-classic-boilerplate/build/extjs/manifest.js:1
[ERR] 
[ERR] BUILD FAILED
[ERR] org.mozilla.javascript.EvaluatorException: Compilation produced 1 syntax errors.
[ERR] 
[ERR] Total time: 2 seconds
[ERR] org.mozilla.javascript.EvaluatorException: Compilation produced 1 syntax errors.
Error: Error building Ext JS bundle
    at /WebServer/myapp/extjs-reactor/packages/reactor-classic-boilerplate/node_modules/@extjs/reactor-webpack-plugin/dist/index.js:194:65
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

**Comment by BlaineBradbury** [comment]
weird...
replaced with:
     value={'<img src="icons/toolbar_find.png"></img>'}

and it builds... after copying the icon to the build directory.

**Comment by BlaineBradbury** [comment]
OK, with the file-loader in place in the webpack.config file, e.g.:
```
                loader: 'file-loader',
                query: {
                    name: '/icons/[name].[ext]'
                }
```

I can import an image from the src directory like so:
```
import toolbar_find from '../../../icons/toolbar_find.png';
```

And then reference it in the value of the DisplayField successfully like so:
```
value={'<img src='+toolbar_find+'></img>'}
```

...good enough!
